### PR TITLE
Create Survival_prediction_titanic.ipynb

### PR DESCRIPTION
**Pull request by anushka645**
Survival Predicted

# Description

Predicted Survival of Passengers travelling on Titanic.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Name it TITANIC_SURVIVAL_PROJECT2
Add some screenshots in the same folder
Add some resource links in the README of the project.

**Comment by anushka645** [comment]
What kind of screenshots do you want me to add?

**Comment by garimasingh128** [comment]
just a screenshot of the final accuracy you get. It can also be an MD file and paste the final metrics in it.

**Comment by garimasingh128** [comment]
Please name the folder TITANIC_SURVIVAL_PROJECT2

**Comment by anushka645** [comment]
Hi @garimasingh128 ,i have made the changes you suggested. Plz let me know if any further changes required.

**Comment by garimasingh128** [comment]
Please name the folder TITANIC_SURVIVAL_PROJECT2 not the python file.

**Comment by anushka645** [comment]
i have already changed the name of folder as Titanic_Survival_Project2 . Do you want me to change the name of ipynb file as well ?

**Comment by garimasingh128** [comment]
https://github.com/anushka645/awesome-python-projects/tree/master/Titanic%20Survival%20Project

Change the name of this to TITANIC_SURVIVAL_PROJECT2 as you can see there is already a Titanic survival project folder in the root and yours will overwrite it.

**Comment by garimasingh128** [comment]
Perfect. Just one last thing. Can you delete the folder Titanic Survival Project from ur forked copy.

**Comment by anushka645** [comment]
This one ?
https://github.com/anushka645/awesome-python-projects/tree/master/Titanic%20Survival%20Project

**Comment by garimasingh128** [comment]
Yup

**Comment by anushka645** [comment]
> Perfect. Just one last thing. Can you delete the folder Titanic Survival Project from ur forked copy.

Done

**Pull request merged**
