### PR TITLE
changes done

### PR DESCRIPTION
**Pull request by anut123**
A sentiment analyzer learns about various sentiments behind a content through machine learning and predicts the same using AI. By creating an ML system that would analyze the sentiment behind texts, or a post, it might become so a lot easier for organizations to know and understand their consumer behavior better. Twitter data is taken into account as an ultimate entry point for beginners to practice sentiment analysis machine learning problems. Using Twitter datasets, one can get a charismatic combination of tweet contents and other related metadata such as hashtags, location, retweets, users, and many more which pave way for insightful analysis. To build a model to classify users’ profile photos as sad happy or neutral.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anut123** [comment]
Hi ma'am,
should I start with new issue or should  I wait because this issue is not merged yet and already 7 days are over.

**Comment by garimasingh128** [comment]
Ya go on and ask for assignment of another issue. I will merge it once I am sure of the code. As a correction, this is not an _issue_ , it is a _Pull request_.

**Comment by anut123** [comment]
Ok ma'am

**Comment by anut123** [comment]
Hi ma'am,
Can you check and accept my pull request and merged it because from
tomorrow onwards we have to show live project and score will be also
declared in that  if my pull request is not accepted and merged it then my
score will not be counted.

**Comment by anut123** [comment]
Issue has been merged ma'am can you close this issue

**Comment by anut123** [comment]
Ma'am can you close this sentiment analyser ML project  because it has been merged also

**Pull request merged**
