### PR TITLE
 secure your password

### PR DESCRIPTION
**Pull request by anut123**
Description 

Added a script (.py) file for secure your password program.
In these program, we have to input a string and it returns the pattern consisting of symbols, to secure our password for example - 'a' it generates '!!'.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [Yes ] My code follows the style guidelines of this project
- [Yes] I have performed a self-review of my own code
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [Yes] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anut123** [comment]
For space and about other symbols -

In dictionary if we add another value ! a blank space ' ' like this and set
it's key to any symbol ! we can also add symbols !
Dictionary {
'a' : '$',
' ' : '+'
} like this

to recognize that the symbol is of alphabet or special symbol -

From dictionary !
We can check for the value and key !
example :-

'o' : '+'

Here o is a value and it's key is + ! When ever user presses o it returns +
symbol ! and same for others.

**Comment by garimasingh128** [comment]
1. Include resources in readme.md file as they are added for existing projects.
2. No plagiarism. If you have copied code, mention the resource in README.
3. Working code. We will check all codes functionality so they should be working and fulfil the purpose.
4. Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
5. Also include screenshot in the folder. Optional but if you want you can include screenshots of your working code in the same folder as above.

P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo. 

FOLLOW THESE STEPS FOR FUTURE PRs ALSO.

**Comment by garimasingh128** [comment]
@anut123  update the title and description of the PR also as per the issue you have solved.

**Comment by anut123** [comment]
Ok ma'am

**Comment by mrinal41298** [comment]
You have to ask for user input and display accordingly. Instead, you just performed the operation on a default string selected by you.

**Comment by anut123** [comment]
sir, please help me out how to do it

**Comment by anut123** [comment]
Ok ma'am

**Comment by anut123** [comment]
The required changes have been made please let me know for the further additions/corrections.
sym = {
          'a' : '!!',
          'b' : '@',
          'c' : '#',
          'd' : '$',
          'e' : '^',
          'f' : '}',
          'g' : ']',
          'h' : ')',
          'i' : '*',
          'j' : '=',
          'k' : '+',
          'l' : '-',
          'm' : '_',
          'n' : '>',
          'o' : '<',
          'p' : '.',
          'q' : '%',
          'r' : '&',
          's' : '(',
          't' : '{',
          'u' : '[',
          'x' : '?',
          'y' : ',',
          'z' : '|',
          }
inp = input("enter your name:")
print(inp)
password = ''

for i in inp:
        for key, val in sym.items():
                if i in key:
                        password = password + val

print("Name you entered : ",inp)
print("Password : ", password)

**Comment by garimasingh128** [comment]
Hey @anut123 Did you make these changes?
Include resources in readme.md file as they are added for existing projects.
Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
Also include screenshot in the folder. 
P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo.

Also the changes in which you have taken user input is not shown in the code. Did you change the file's code?

**Comment by anut123** [comment]
No ma'am, i haven't change the file code because the code is already
uploaded so the changes i had made just now with the user input i just
paste the code in comment section and how to change the file code and how
to create separate folder in github and how to include screenshot folder in
that?

**Comment by garimasingh128** [comment]
In your local Project, just change the code and make a folder. In that folder just put your python file and the screenshot of the output from the terminal. Then open README file and add the resources in it like other resources are added for other projects. After that do git add . and git commit -m "message". Your pull request will be updated automatically so you don't need to do anything else then.

**Comment by anut123** [comment]
ok ma'am but i don't know how to use git bash and all so can i do directly
with github?

**Comment by garimasingh128** [comment]
You should learn it first as it's very important. For now, make the changes in your project locally and upload the files by drag and drop on github in your forked repository. The pr will update automatically.

**Comment by anut123** [comment]
ok ma'am,  i will do now.

**Comment by anut123** [comment]
completed all the corrections.

**Comment by garimasingh128** [comment]
- Rename the folder from URL_SHORTENER to SECURE_YOUR_PASSWORD.
- Add the python file in the folder as well
- you dont have to create your own README. Add the resources in the README present in the root of the project just like other resources are added.

**Comment by anut123** [comment]
Ma'am how to these add the resources in the README present in the root of the project just like other resources are added how to do these i tired my best but i couldnot do it.

**Comment by anut123** [comment]
Ma'am how to do these add the resources in the README present in the root of the project just like other resources are added how to do these i tired my best but i couldnot do it.

**Comment by anut123** [comment]
Ma'am how to add the resources in the README present in the root of the project just like other resources are added how to do these i tired my best but i couldnot do it.

**Comment by anut123** [comment]
Done with the corrections please let me know in case of any changes.

**Comment by garimasingh128** [comment]
> * Rename the folder from URL_SHORTENER to SECURE_YOUR_PASSWORD.
> * Add the python file in the folder as well
> * you dont have to create your own README. Add the resources in the README present in the root of the project just like other resources are added.

Did you made these changes? I can't see them.

**Comment by anut123** [comment]
yes ma'am i made the changes but here it is showing like these garimasingh128:master from unknown repository

**Comment by garimasingh128** [comment]
try creating another PR

**Comment by anut123** [comment]
yes ma'am i made the changes and refresh again please let me know

**Comment by anut123** [comment]
ok ma'am is rest everything  correct?

**Pull request closed without merging**
