### PR TITLE
Guess the number

### PR DESCRIPTION
**Pull request by Gomathi-P**
# Description

I have created a project on guessing the number from 1 to 20 which is the issue that i have choosed in awesome python project

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
I have tested it using google colab manually and tried it with different conditions it worked without an error.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ yes] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ yes] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Include resources in readme.md file as they are added for existing projects.
No plagiarism. If you have copied code, mention the resource in README.
Working code. We will check all codes functionality so they should be working and fulfil the purpose.
Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
Also include screenshot in the folder. Optional but if you want you can include screenshots of your working code in the same folder as above.
P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo.

Change your PR Title and description according to the issue you have solved!

FOLLOW THESE STEPS FOR FUTURE PRs ALSO.

**Comment by garimasingh128** [comment]
> Include resources in readme.md file as they are added for existing projects.
> No plagiarism. If you have copied code, mention the resource in README.
> Working code. We will check all codes functionality so they should be working and fulfil the purpose.
> Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
> Also include screenshot in the folder. Optional but if you want you can include screenshots of your working code in the same folder as above.
> P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo.
> 
> Change your PR Title and description according to the issue you have solved!
> 
> FOLLOW THESE STEPS FOR FUTURE PRs ALSO.

@Gomathi-P ????

**Comment by Gomathi-P** [comment]
I will try to finish it mam

**Comment by garimasingh128** [comment]
@Gomathi-P can u create final pr or should I close this?

**Comment by Gomathi-P** [comment]
Mam you can close it

**Pull request closed without merging**
