### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by ayushsurana710**
# Description

I have added a model which would predict Credit card Fraud Detection. I also have attached the dataset and reference for my code . I request you to review my pull request.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Name it TCREDIT_CARD_FRAUD_DETECTION
Add some screenshots in the same folder
Add some resource links in the README of the project. Dont create a separate readme.

**Comment by ayushsurana710** [comment]
Hello Garima ,
I didn't understand what screenshot I have attach . I request you to
clarify this.

Thanking you

Regards ,
Ayush Surana

**Comment by garimasingh128** [comment]
just a screenshot of the final accuracy you get. It can also be an MD file and paste the final metrics in it.

**Comment by ayushsurana710** [comment]
Thank you for clarification . I will do the necessary changes and will send
the pull request again.

**Comment by garimasingh128** [comment]
No need to send another PR. Just do the changes in your fork and this PR will automatically be updated.

**Comment by ayushsurana710** [comment]
Thank you . I will do that and revert back to you.

Regards ,
Ayush Surana
ᐧ

**Comment by ayushsurana710** [comment]
Hello Garima,
I have made a new pull request as I don't know how to do change in a
already existing pull request . I request you to review my pull request .

Regards ,
Ayush Surana

**Pull request closed without merging**
