### PR TITLE
Created Rolling Dice Program

### PR DESCRIPTION
**Pull request by yogi6591**
# Description
I have created rolling dice program listed as an issue,with all the condition and requirement written there. 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
Rolling Dice

## Type of change
No change in any other files.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update   

# How Has This Been Tested?

I have tested it manually in different different conditions and inputs,so i think this code will work in any case without any error.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A   
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain: 
* SDK: 

# Checklist:

- [ yes] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [no ] I have made corresponding changes to the documentation
- [ yes] My changes generate no new warnings
- [no ] I have added tests that prove my fix is effective or that my feature works
- [yes ] New and existing unit tests pass locally with my changes
- [no ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
1. Include resources in readme.md file as they are added for existing projects.
2. No plagiarism. If you have copied code, mention the resource in README.
3. Working code. We will check all codes functionality so they should be working and fulfil the purpose.
4. Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
5. Also include screenshot in the folder. Optional but if you want you can include screenshots of your working code in the same folder as above.

P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo. 

FOLLOW THESE STEPS FOR FUTURE PRs ALSO.

**Comment by yogi6591** [comment]
I have added screenshots and removed .idea folder as you asked to do it.
Please check it now.

**Comment by garimasingh128** [comment]
please do a git pull as its showing merge conflicts rn.

**Comment by yogi6591** [comment]
i did it before commiting and after pusing as well,it showed me it is up to date.

**Comment by garimasingh128** [comment]
Added your code manually due to some unresolved merge conflicts. The contribution will be counted for the final score.

**Pull request closed without merging**
