### PR TITLE
Added titanic-solution

### LINKED ISSUE #53: Titanic Survival Project
Titanic Survival Project
Project idea – This will be a fun project to build as we will be predicting whether someone would have survived if they were in the titanic ship or not. For this beginner’s project, we will use the Titanic dataset that contains real data of the survivors and people who died in the Titanic ship.

https://www.kaggle.com/c/titanic

### PR DESCRIPTION
**Pull request by Dhruv-VINT**
# Description

I have added a new ipynb notebook for Titanic survival project in which I have performed EDA on what sorts of people were likely to survive. Also used various ML algorithms to predict which passengers survived & displayed it in results/submissions.
Please review @garimasingh128 

Fixes #53  (Titanic Survival Project)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
- Name it TITANIC_SURVIVAL_PROJECT
- Add some screenshots in the same folder
- Add some resource links in the README of the project.

**Comment by Dhruv-VINT** [comment]
Should I put my screenshots in the 'Screenshot' folder ?
and also I have to add resource links in the main README of the project folder, right ? @garimasingh128

**Comment by garimasingh128** [comment]
Put screenshots in TITANIC_SURVIVAL_PROJECT folder and resource links in main readme.

**Comment by Dhruv-VINT** [comment]
Changes made, please check if everything's in place @garimasingh128

**Comment by garimasingh128** [comment]
Please name the folder to caps to TITANIC_SURVIVAL_PROJECT2. There's already a project with the same name so yours would overwrite it that's why the 2 at the end.
Add the resource links to the main readme of the file. If you scroll to the bottom there you would see links to many projects, Add your reference links at the last.

**Comment by Dhruv-VINT** [comment]
There you go

**Comment by Dhruv-VINT** [comment]
What's the problem now ? @garimasingh128

**Comment by garimasingh128** [comment]
Conflicting files
Titanic Survival Project/README.md

And change the folder name to TITANIC_SURVIVAL_PROJECT

**Comment by Dhruv-VINT** [comment]
What's the issue with README.md file, I dont understand @garimasingh128

**Comment by garimasingh128** [comment]
Can u change the folder name and delete the existing folder. I can resolve the README conflict after that. Or maybe create a fresh PR and close this one.

**Comment by Dhruv-VINT** [comment]
okay so you mean delete that TITANIC_SURVIVAL_PROJECT2, and name it with the original one, I guess someone messed up that one

**Comment by garimasingh128** [comment]
Nope that is fine. Just rename your Titanic Survival Project folder to TITANIC_SURVIVAL_PROJECT and create a new PR.

**Comment by garimasingh128** [comment]
Please do this asap.

**Comment by Dhruv-VINT** [comment]
I've had an health emergency in my family. Can you please give me time for just this week. I'll be back on Sunday

**Comment by garimasingh128** [comment]
Ya sure. Please take your time. Family first.

**Review by garimasingh128 — APPROVED** [review]

**Pull request closed without merging**
