### PR TITLE
added IPL score predictor

### PR DESCRIPTION
**Pull request by Shobhit-aryan**
# Description
Domain - Machine Learning
Algorithm Used - Linear regression with good accuracy and least error compared to other regression algorithms
Dataset contains IPL data from 2008 to 2019 with different features like - 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker', 'non-striker', 'total'
Performed exploratory data analysis and selected only required features.

##Added new project to the repo

### CODE REVIEW

**Comment by garimasingh128** [comment]
- Add resources to readme
- add screenshots to folder

Refer https://github.com/garimasingh128/awesome-python-projects/pull/32

**Comment by garimasingh128** [comment]
Add some resources links in the readme of the repo

**Comment by Shobhit-aryan** [comment]
Added end to end project.
Added Readme.md file and some screenshots
Added reference links

**Comment by Shobhit-aryan** [comment]
Updated all the required resources and files. Can you merge my branch to
the master branch after verifying it?

**Pull request merged**
