### PR TITLE
Sentiment analyser ML project

### PR DESCRIPTION
**Pull request by anut123**
A sentiment analyzer learns about various sentiments behind a content through machine learning and predicts the same using AI. By creating an ML system that would analyze the sentiment behind texts, or a post, it might become so a lot easier for organizations to know and understand their consumer behavior better. Twitter data is taken into account as an ultimate entry point for beginners to practice sentiment analysis machine learning problems. Using Twitter datasets, one can get a charismatic combination of tweet contents and other related metadata such as hashtags, location, retweets, users, and many more which pave way for insightful analysis. To build a model to classify users’ profile photos as sad happy or neutral.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Please put all images in a single folder inside sentiment analysis folder as there are too many. @mrinal41298 Can you review the code base?

**Comment by anut123** [comment]
Images are already uploaded in folder only

**Comment by garimasingh128** [comment]
I meant in a separate images folder inside the sentiment analysis folder.

**Comment by anut123** [comment]
okay ma'am

**Comment by anut123** [comment]
In separate images folder should i add all the images or i should delete some images because in output screenshot we can see the output of the code.

**Comment by garimasingh128** [comment]
Just put all the images in the images folder inside the root. and Code files in the root folder.

**Pull request closed without merging**
