### PR TITLE
rock_paper_scissor (game)

### PR DESCRIPTION
**Pull request by pranesh-badarinath**
# Description
Added a script (.py) file for the Rock Paper Scissor game. 
It takes input from the user and generates a random input for CPU, and compares the result and generates the output accordingly.
1. user input (player 1).
2. comparing the input with random self-generated input by CPU(player 2).
3. Displaying the result.
4. Asking the user whether he wishes to continue the game or not.
(For each iteration, it asks the user whether the user wishes to continue or not )
code is developed using python 3.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Edit the description to fit your PR.

**Comment by pranesh-badarinath** [comment]
updated

**Comment by garimasingh128** [comment]
1. Include resources in readme.md file as they are added for existing projects.
2. No plagiarism. If you have copied code, mention the resource in README.
3. Working code. We will check all codes functionality so they should be working and fulfil the purpose.
4. Separate folder by correct name and inside it all the files. Make a separate folder like URL_SHORTENER and put all the python and related files in it even if there's a single file.
5. Also include screenshot in the folder. Optional but if you want you can include screenshots of your working code in the same folder as above.

P.S. You dont need to close your existing PRs. Just push the changes in your forked repo and they will automatically get updated in my repo. 

FOLLOW THESE STEPS FOR FUTURE PRs ALSO.

**Comment by garimasingh128** [comment]
@pranesh-badarinath  did u make the changes? The timeline is 1 week per project. It's way past the timeline.

**Comment by pranesh-badarinath** [comment]
By today evening I ll updade the changes.

**Comment by garimasingh128** [comment]
Perfect! Good job

**Comment by pranesh-badarinath** [comment]
thank you

**Comment by garimasingh128** [comment]
@pranesh-badarinath I think you forgot to add resources in README. Create a separate PR to just add some resources!

**Pull request merged**
