### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anut123**
secure your password

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Edit the template to fit the PR's description!

**Comment by anut123** [comment]
Hi ma'am,
How to cancel the pull request i have to upload the file can i do it again?

**Comment by garimasingh128** [comment]
You don't need to cancel the PR. Whatever you upload on your forked repo will be updated automatically in this PR so you don't need to create PRs' again and again. I asked you to edit the template description to fit your Pr like which issue it solves etc.

**Comment by anut123** [comment]
ma'am by mistake i uploaded .txt file instead of that i have to upload .py

**Comment by garimasingh128** [comment]
No issues. Delete that file from your repo and add the python file. The PR will get updated by itself.

**Comment by anut123** [comment]
ok ma'am

**Pull request closed without merging**
