### PR TITLE
changes done

### PR DESCRIPTION
**Pull request by anut123**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
You renamed README to Updated README.md. Rename it to README only. Also close the previous PR.

**Comment by anut123** [comment]
Changes done ma'am now everything is correct?

**Comment by anut123** [comment]
changes done ma'am now everything is correct?

**Comment by garimasingh128** [comment]
You forgot to update the README. Just add 3-4 resources as below under your projects name as they are present currently as below.
Screenshot (559)

**Comment by anut123** [comment]
ok ma'am

**Comment by anut123** [comment]
changes done ma'am now everything is correct?

**Comment by anut123** [comment]
Resources are added ma'am now everything is correct?

**Comment by anut123** [comment]
added resources

**Comment by garimasingh128** [comment]
Perfect!

**Comment by anut123** [comment]
How to merged into master?

**Comment by garimasingh128** [comment]
That is my task. I have merged it already. You can see your changes in the master branch!

**Comment by anut123** [comment]
Ok ma'am

**Comment by anut123** [comment]
Now everything is Completed or still remaining to complete ?

**Pull request merged**
