### PR TITLE
README

### PR DESCRIPTION
**Pull request by pranesh-badarinath**
# Description
-The added file contains the description of the project and the related articles used for building the same. 

# Checklist:

- [ 1] My code follows the style guidelines of this project
- [ 1] I have performed a self-review of my own code
- [ 1] I have commented on my code, particularly in hard-to-understand areas
- [ 1] I have made corresponding changes to the documentation
- [1 ] My changes generate no new warnings
- [ 1] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranesh-badarinath** [comment]
updated with resources used in building a project.

**Comment by garimasingh128** [comment]
Just add like below in the README of the project only. No need to create a separate README.
Screenshot (559)

**Comment by pranesh-badarinath** [comment]
updated with the resources in the readme.md file

**Comment by garimasingh128** [comment]
Do a git pull first. It is showing merge conflicts!

**Comment by pranesh-badarinath** [comment]
Do I need to open a pull request on updating readme. md file

**Comment by garimasingh128** [comment]
No, just do a single git pull or fetch from my master branch and again commit the changes with git add . and git commit -m "meessage". Then do git push origin master. This will automatically update this PR. Actually I did some changes in README and your README doesn't have those changes so merge conflicts are arising!

**Pull request closed without merging**
