### PR TITLE
Simple Calculator

### PR DESCRIPTION
**Pull request by pranesh-badarinath**
# Description
PROJECT NAME: SIMPLE CALCULATOR
PROJECT ID: #39
 
Added .py file having a calculator application.
SIMPLE CALCULATOR THAT CAN PERFORM FOLLOWING OPERATIONS
 BASIC OPERATIONS
1. ADDITION
2. SUBTRACTION
3. MULTIPLICATION
4. DIVISION
5. MODULUS

 ADVANCED OPERATIONS
1. NATURAL LOG
2. TRIGONOMETRIC CALCULATIONS
3. EXPONENTIAL CALCULATIONS

Please delete options that are not relevant.

- [ 1] Bug fix (non-breaking change which fixes an issue)
- [ 1] New feature (non-breaking change which adds functionality)
- [ 1] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ 1] This change requires a documentation update

# How Has This Been Tested?

The code is tested with zero complications in VS_Code and Jupiter notebook environment.

CODE DEVELOPMENT  :
1. Tkinter
2. python 3

# Checklist:

- [ 1] My code follows the style guidelines of this project
- [ 1] I have performed a self-review of my own code
- [ 1] I have commented on my code, particularly in hard-to-understand areas
- [ 1] I have made corresponding changes to the documentation
- [ 1] My changes generate no new warnings
- [ 1] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by pranesh-badarinath** [comment]
updated with a simple calculator application.

**Comment by garimasingh128** [comment]
Add the references to readme in a proper format!

**Comment by pranesh-badarinath** [comment]
updated readme.Md

**Comment by garimasingh128** [comment]
The changes are not visible. MAKE SURE YOU ADDED AND COMMITTED THEM!

**Comment by pranesh-badarinath** [comment]
@garimasingh128  
I updated readme.MD with the resources i used....
Thank you

**Comment by garimasingh128** [comment]
Resolve the conflicts: Conflicting files
README.md

Also in README, the bullets should be:
- https://... and not -https://.....

**Comment by garimasingh128** [comment]
Still has some conflicts in README, just pull it once.

**Comment by pranesh-badarinath** [comment]
@garimasingh128 
I think it is resolved, ma'am

**Comment by garimasingh128** [comment]
Perfect.

**Pull request merged**
